# Generated by Django 4.2.16 on 2024-11-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_verified_customuser_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_code',
        ),
    ]
