# Generated by Django 4.2.16 on 2024-11-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_username',
            field=models.CharField(blank=True, default='edulb96', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, default='Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default='Last name', max_length=255),
        ),
    ]
