# Generated by Django 4.2.23 on 2025-06-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_admin_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='number_designs_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number_executed_scenarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number_times_connected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number_times_modified_password',
            field=models.IntegerField(default=0),
        ),
    ]
