# Generated by Django 4.2.18 on 2025-01-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_scenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(blank=True, default='Scenario name', max_length=255),
        ),
    ]
