# Generated by Django 4.2.18 on 2025-01-29 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_alter_scenario_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='status',
            field=models.CharField(default='Draft', max_length=255),
        ),
        migrations.AddField(
            model_name='scenario',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
