# Generated by Django 4.2.18 on 2025-02-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0004_scenario_status_scenario_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('red', 'Network')], max_length=10)),
                ('entry_count', models.IntegerField(default=0)),
                ('content', models.FileField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'File',
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_management.file'),
        ),
    ]
