# Generated by Django 4.2.19 on 2025-02-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0005_file_scenario_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyDetector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_management.scenario')),
            ],
            options={
                'db_table': 'AnomalyDetector',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField()),
                ('precission', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1score', models.FloatField()),
                ('confusion_matrix', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('detector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_management.anomalydetector')),
            ],
            options={
                'db_table': 'Metric',
            },
        ),
    ]
