# Generated by Django 4.2.19 on 2025-02-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0006_anomalydetector_metric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='precission',
            new_name='precision',
        ),
        migrations.AddField(
            model_name='metric',
            name='model_name',
            field=models.CharField(default='model_name', max_length=255),
        ),
    ]
