# Generated by Django 4.2.19 on 2025-02-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0007_rename_precission_metric_precision_metric_model_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='f1score',
            new_name='f1_score',
        ),
    ]
