# Generated by Django 4.2.19 on 2025-02-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0008_rename_f1score_metric_f1_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='metric',
            name='f1_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='metric',
            name='precision',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='metric',
            name='recall',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
