# Generated by Django 4.2.19 on 2025-02-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0009_alter_metric_accuracy_alter_metric_f1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='references',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(upload_to='files/'),
        ),
    ]
