# Generated by Django 4.2.19 on 2025-02-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0010_file_references_alter_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='confusion_matrix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='f1_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='precision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='recall',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
