# Generated by Django 4.2.19 on 2025-03-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0011_alter_metric_accuracy_alter_metric_confusion_matrix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalydetector',
            name='execution',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='execution',
            field=models.IntegerField(default=0),
        ),
    ]
