# Generated by Django 4.2.20 on 2025-03-20 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0012_anomalydetector_execution_metric_execution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Metric',
            new_name='ClassificationMetric',
        ),
        migrations.AlterModelTable(
            name='classificationmetric',
            table='ClassificationMetric',
        ),
        migrations.CreateModel(
            name='AnomalyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution', models.IntegerField()),
                ('model_name', models.CharField(default='model_name', max_length=255)),
                ('feature_name', models.CharField(max_length=255)),
                ('anomalies', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.anomalydetector')),
            ],
            options={
                'db_table': 'AnomalyMetric',
            },
        ),
    ]
