# Generated by Django 4.2.20 on 2025-03-20 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0013_rename_metric_classificationmetric_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomalymetric',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.CreateModel(
            name='RegressionMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution', models.IntegerField(default=0)),
                ('model_name', models.CharField(default='model_name', max_length=255)),
                ('mse', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('rmse', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('mae', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('r2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('msle', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('detector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_management.anomalydetector')),
            ],
            options={
                'db_table': 'RegressionMetric',
            },
        ),
    ]
