# Generated by Django 4.2.21 on 2025-05-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0014_rename_timestamp_anomalymetric_date_regressionmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalymetric',
            name='production',
            field=models.BooleanField(default=False),
        ),
    ]
