# Generated by Django 4.2.21 on 2025-05-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0015_anomalymetric_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='file',
        ),
        migrations.AddField(
            model_name='scenario',
            name='files',
            field=models.ManyToManyField(blank=True, to='data_management.file'),
        ),
    ]
