# Generated by Django 4.2.21 on 2025-05-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0016_remove_scenario_file_scenario_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='files',
        ),
        migrations.AddField(
            model_name='scenario',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_management.file'),
        ),
    ]
