# Generated by Django 4.2.23 on 2025-06-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0018_remove_scenario_file_scenario_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalymetric',
            name='anomaly_image',
            field=models.ImageField(blank=True, null=True, upload_to='anomaly_images/'),
        ),
        migrations.AddField(
            model_name='anomalymetric',
            name='global_shap_image',
            field=models.ImageField(blank=True, null=True, upload_to='shap_global_images/'),
        ),
        migrations.AddField(
            model_name='anomalymetric',
            name='local_shap_image',
            field=models.ImageField(blank=True, null=True, upload_to='shap_local_images/'),
        ),
    ]
