# Generated by Django 4.2.23 on 2025-06-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0019_anomalymetric_anomaly_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalymetric',
            name='global_lime_image',
            field=models.ImageField(blank=True, null=True, upload_to='lime_global_images/'),
        ),
        migrations.AddField(
            model_name='anomalymetric',
            name='local_lime_image',
            field=models.ImageField(blank=True, null=True, upload_to='lime_local_images/'),
        ),
    ]
