# Generated by Django 4.2.23 on 2025-07-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0020_anomalymetric_global_lime_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomalymetric',
            name='anomaly_image',
        ),
        migrations.AddField(
            model_name='anomalymetric',
            name='anomaly_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
