# Generated by Django 4.2.23 on 2025-07-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0021_remove_anomalymetric_anomaly_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomalymetric',
            name='global_shap_image',
        ),
        migrations.AddField(
            model_name='anomalymetric',
            name='global_shap_images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
