# Generated by Django 4.2.23 on 2025-07-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0022_remove_anomalymetric_global_shap_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomalymetric',
            name='global_lime_image',
        ),
        migrations.RemoveField(
            model_name='anomalymetric',
            name='local_lime_image',
        ),
        migrations.RemoveField(
            model_name='anomalymetric',
            name='local_shap_image',
        ),
        migrations.AddField(
            model_name='anomalymetric',
            name='global_lime_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anomalymetric',
            name='local_shap_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationmetric',
            name='global_lime_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationmetric',
            name='global_shap_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationmetric',
            name='local_shap_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regressionmetric',
            name='global_lime_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regressionmetric',
            name='global_shap_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regressionmetric',
            name='local_shap_images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
