# Generated by Django 4.2.23 on 2025-07-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0023_remove_anomalymetric_global_lime_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalymetric',
            name='local_lime_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationmetric',
            name='local_lime_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regressionmetric',
            name='local_lime_images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
