# Generated by Django 4.2.23 on 2025-07-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0024_anomalymetric_local_lime_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalymetric',
            name='packet_images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
