# Generated by Django 4.2.23 on 2025-07-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0025_anomalymetric_packet_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomalymetric',
            name='packet_images',
        ),
    ]
