# Generated by Django 4.2.23 on 2025-07-22 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0026_remove_anomalymetric_packet_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataController',
        ),
        migrations.DeleteModel(
            name='DataFilter',
        ),
        migrations.DeleteModel(
            name='DataMixer',
        ),
        migrations.DeleteModel(
            name='DataReceiver',
        ),
        migrations.DeleteModel(
            name='DataStorage',
        ),
        migrations.DeleteModel(
            name='DataSync',
        ),
    ]
