# Generated by Django 4.2.24 on 2025-09-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0027_delete_datacontroller_delete_datafilter_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnomalyDetector',
            new_name='ScenarioModel',
        ),
        migrations.RenameField(
            model_name='anomalymetric',
            old_name='detector',
            new_name='scenario_model',
        ),
        migrations.RenameField(
            model_name='classificationmetric',
            old_name='detector',
            new_name='scenario_model',
        ),
        migrations.RenameField(
            model_name='regressionmetric',
            old_name='detector',
            new_name='scenario_model',
        ),
        migrations.AlterModelTable(
            name='scenariomodel',
            table='ScenarioModel',
        ),
    ]
