# Generated by Django 4.2.16 on 2024-10-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ActionController', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ActionReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ActionReceiver', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ActionSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ActionSync', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerformAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PerformAction', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PolicyManagement', max_length=100)),
            ],
        ),
    ]
