# Generated by Django 4.2.23 on 2025-07-22 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action_execution', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionController',
        ),
        migrations.DeleteModel(
            name='ActionReceiver',
        ),
        migrations.DeleteModel(
            name='ActionSync',
        ),
        migrations.DeleteModel(
            name='PerformAction',
        ),
        migrations.DeleteModel(
            name='PolicyManagement',
        ),
    ]
