/**
 * @summary Interface representing a scenario within the application.
 * 
 * A scenario defines a specific configuration or pipeline to be executed,
 * including its metadata, design structure, status, and creation date.
 */
export interface Scenario {
    /** @summary Unique numerical identifier of the scenario (primary key) */
    id: number;
  
    /** @summary Human-readable name of the scenario */
    name: string;
  
    /** 
     * @summary The full design structure of the scenario.
     * 
     * This object contains the serialized visual graph (nodes, connections, etc.)
     * typically generated by the scenario builder.
     */
    design: object;
  
    /** @summary Universally unique identifier for the scenario (used in routing and references) */
    uuid: string;
  
    /** 
     * @summary Current execution status of the scenario.
     * 
     * - `Draft`: not yet executed  
     * - `Running`: currently executing  
     * - `Finished`: completed successfully  
     * - `Error`: execution failed  
     */
    status: 'Draft' | 'Running' | 'Finished' | 'Error';
  
    /** @summary ISO-formatted creation or last update timestamp (e.g., "2025-07-23T14:35:00Z") */
    date: string;
  }  