# Generated by Django 4.2.23 on 2025-07-21 11:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='System',
            new_name='SystemConfiguration',
        ),
        migrations.AlterModelTable(
            name='systemconfiguration',
            table='SystemConfiguration',
        ),
    ]
