# Generated by Django 4.2.27 on 2026-01-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_monitor', '0002_rename_system_systemconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='bpftrace_script_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
